#!/bin/bash -e

git clone git@iis-git.ee.ethz.ch:pulp-tests/ml_tests.git
git clone git@iis-git.ee.ethz.ch:pulp-sw/pulp_tests.git
git clone git@iis-git.ee.ethz.ch:pulp-tests/rt-tests.git
git clone git@iis-git.ee.ethz.ch:pulp-sw/parallel_bare_tests.git
git clone git@iis-git.ee.ethz.ch:pulp-sw/riscv_tests.git
git clone git@iis-git.ee.ethz.ch:pulp-sw/sequential_bare_tests.git