#!/bin/bash -e

if [ ! -e   tests/marsellus_tests ]; then
git clone git@iis-git.ee.ethz.ch:marsellus/marsellus_tests.git \
    tests/marsellus_tests
else
pushd tests/marsellus_tests
git checkout jetcas
git pull
popd
fi
