set_false_path -from [get_pins {ulpsoc_i/cluster_i/ulpcluster_i/cluster_int_region_i/cluster_peripherals_i/cluster_control_unit_i/r_fetch_en_reg[*]/C}]
set_false_path -from [get_pins ulpsoc_i/cluster_i/ulpcluster_i/rstgen_i/s_rst_n_reg/C]
set_false_path -from [get_pins ulpsoc_i/i_clk_rst_gen/i_rst_gen_soc/s_rst_n_reg/C]
set_false_path -through [get_nets {ulpsoc_i/i_clk_rst_gen/rstn_cluster_sync_o}]
set_false_path -through [get_nets {ulpsoc_i/i_clk_rst_gen/rstn_sync_o}]
#set_false_path -from [get_clocks {ref_clk_i}] -to [get_clocks {ulpsoc_clk}]
#set_false_path -from [get_clocks {ulpsoc_clk}] -to [get_clocks {ref_clk_i}]
#set_false_path -from [get_clocks {spi_clk}] -to [get_clocks {ulpsoc_clk}]
#set_false_path -from [get_clocks {ulpsoc_clk}] -to [get_clocks {spi_clk}]
#set_false_path -from [get_clocks {ref_clk_i}] -to [get_clocks {spi_clk}]
#set_false_path -from [get_clocks {spi_clk}] -to [get_clocks {ref_clk_i}]
